<?php

require_once 'ISuperUser.class.php';

class SuperUser extends User implements ISuperUser {
    public $role;
    public static $countObjSupUser = 0;


    function __construct($n, $l, $p, $r) {
         self::$countObjSupUser++;

        //echo __CLASS__;

        parent::__construct($n, $l, $p);
        $this->role = $r;
    }

    function  showInfo()
    {
        parent::showInfo(); // TODO: Change the autogenerated stub
        echo "Роль: {$this->role}\n";

    }

    //возвращает ассоциативный массив, в котором именами ¤чеек ¤вл¤ютс¤ имена свойств объекта,
    // а значени¤ми ¤чеек - значени¤ свойств объекта
    function getInfo() {
        $array =[];
        foreach ($this as $key=>$value){
            $array[$key] = $value;
        }
        return $array;
    }

}